name: deck_of_card_memo
description: Flutter card memorization app with 2D/3D card display and interactive quiz functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_3d_controller: ^1.3.0
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.4
  build_test: ^2.2.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  
  assets:
    - assets/cards/images/
    - assets/cards/models/
    - assets/cards/names.csv
    - assets/ui/icons/
    - assets/ui/backgrounds/
    - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic